### ISSUE TITLE
Maze not clearing on boss kill

### ISSUE THREAD

**Issue by fractalmuse** [Korzer420/CurseRandomizer#4]
Killed False Knight (full fight) after picking up maze but it didn't clear the curse.

If it makes a difference, I did benchwarp after picking the curse up

**Comment by Korzer420** [comment]
The curse only recognize bosses by their hp, which I set to be at least 200. This is why False Knight doesn't count. Will be fixed in the next patch

**Comment by Korzer420** [comment]
Ok the false knight code is too spaghetti to implement that here. I added Vengefly King, Gruz Mother and MMC though. But False Knight will remain unaccountable.
